# Generated by Django 2.2.7 on 2020-03-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
