# Generated by Django 2.2.7 on 2020-03-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
    ]
