# Generated by Django 3.0.5 on 2020-04-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200425_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
