# Generated by Django 2.2.7 on 2020-04-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(upload_to=''),
        ),
    ]
