# Generated by Django 3.0.5 on 2020-04-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200423_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
